# Generated by Django 4.2.7 on 2025-11-21 08:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0006_worktask'),
        ('contracts', '0007_alter_translationcontract_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCategoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_group', models.CharField(choices=[('dich_thuat', 'Dịch thuật'), ('bien_tap', 'Biên tập'), ('cntt', 'CNTT'), ('hanh_chinh', 'Hành chính'), ('khac', 'Khác')], db_index=True, max_length=50, verbose_name='Nhóm công việc')),
                ('category_code', models.CharField(db_index=True, max_length=100, verbose_name='Mã hạng mục')),
                ('category_name', models.CharField(max_length=200, verbose_name='Tên hạng mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('can_view_roles', models.JSONField(default=list, help_text='Danh sách roles có thể xem hạng mục này', verbose_name='Roles có thể xem')),
                ('can_create_roles', models.JSONField(default=list, help_text='Danh sách roles có thể tạo thanh toán cho hạng mục này', verbose_name='Roles có thể tạo')),
                ('can_approve_roles', models.JSONField(default=list, help_text='Danh sách roles có thể phê duyệt thanh toán cho hạng mục này', verbose_name='Roles có thể phê duyệt')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Yêu cầu phê duyệt')),
                ('approval_workflow', models.JSONField(default=dict, help_text='Cấu hình quy trình phê duyệt (ví dụ: {"levels": 1, "auto_approve_amount": 10000000})', verbose_name='Quy trình phê duyệt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Cấu hình hạng mục thanh toán',
                'verbose_name_plural': 'Cấu hình hạng mục thanh toán',
                'db_table': 'payment_category_configs',
                'ordering': ['work_group', 'category_code'],
                'indexes': [models.Index(fields=['work_group', 'is_active'], name='idx_payment_cat_work_active'), models.Index(fields=['category_code'], name='idx_payment_cat_code')],
                'unique_together': {('work_group', 'category_code')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_group', models.CharField(choices=[('dich_thuat', 'Dịch thuật'), ('bien_tap', 'Biên tập'), ('cntt', 'CNTT'), ('hanh_chinh', 'Hành chính'), ('khac', 'Khác')], db_index=True, max_length=50, verbose_name='Nhóm công việc')),
                ('payment_category', models.CharField(db_index=True, max_length=100, verbose_name='Hạng mục thanh toán')),
                ('payment_type', models.CharField(help_text='Ví dụ: Tạm ứng lần 1, Tạm ứng lần 2, Quyết toán', max_length=50, verbose_name='Loại thanh toán')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Loại tiền tệ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('recipient_type', models.CharField(help_text='translator, expert, editor, etc.', max_length=50, verbose_name='Loại người nhận')),
                ('status', models.CharField(choices=[('pending', 'Chờ phê duyệt'), ('approved', 'Đã phê duyệt'), ('rejected', 'Đã từ chối'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('request_date', models.DateField(db_index=True, verbose_name='Ngày yêu cầu')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='Ngày phê duyệt')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL, verbose_name='Người phê duyệt')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.translationcontract', verbose_name='Hợp đồng')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payments', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='works.translationwork', verbose_name='Tác phẩm')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['work_group', 'status'], name='idx_payments_group_status'), models.Index(fields=['payment_category', 'status'], name='idx_payments_cat_status'), models.Index(fields=['recipient', 'status'], name='idx_payments_recipient_status'), models.Index(fields=['request_date'], name='idx_payments_request_date'), models.Index(fields=['status'], name='idx_payments_status')],
            },
        ),
    ]
