# Generated by Django 4.2.7 on 2025-11-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('chu_nhiem', 'Chủ nhiệm'), ('pho_chu_nhiem', 'Phó Chủ nhiệm'), ('truong_ban_thu_ky', 'Trưởng ban Thư ký'), ('thu_ky_hop_phan', 'Thư ký hợp phần'), ('van_phong', 'Văn phòng'), ('ke_toan', 'Kế toán'), ('van_thu', 'Văn thư'), ('bien_tap_vien', 'Biên tập viên (BTV)'), ('ky_thuat_vien', 'Kỹ thuật viên (KTV)'), ('dich_gia', 'Dịch giả'), ('chuyen_gia', 'Chuyên gia'), ('phu_trach_nhan_su', 'Phụ trách Nhân sự')], default='thu_ky_hop_phan', max_length=50, verbose_name='Vai trò'),
        ),
    ]
