# Generated by Django 4.2.7 on 2025-11-14 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên hợp phần')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã hợp phần')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_parts', to=settings.AUTH_USER_MODEL, verbose_name='Trưởng hợp phần')),
            ],
            options={
                'verbose_name': 'Hợp phần dịch thuật',
                'verbose_name_plural': 'Hợp phần dịch thuật',
                'db_table': 'translation_parts',
            },
        ),
        migrations.CreateModel(
            name='TranslationWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Tên tác phẩm')),
                ('name_original', models.CharField(blank=True, max_length=500, verbose_name='Tên gốc')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Tác giả')),
                ('source_language', models.CharField(default='Hán văn', max_length=50, verbose_name='Ngôn ngữ nguồn')),
                ('target_language', models.CharField(default='Tiếng Việt', max_length=50, verbose_name='Ngôn ngữ đích')),
                ('page_count', models.IntegerField(default=0, verbose_name='Số trang cơ sở')),
                ('word_count', models.IntegerField(default=0, verbose_name='Số từ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('state', django_fsm.FSMField(choices=[('draft', 'Dự kiến'), ('approved', 'Đã duyệt'), ('translator_assigned', 'Đã gán dịch giả'), ('trial_translation', 'Dịch thử'), ('trial_reviewed', 'Đã thẩm định dịch thử'), ('contract_signed', 'Đã ký hợp đồng'), ('in_progress', 'Đang dịch'), ('progress_checked', 'Đã kiểm tra tiến độ'), ('final_translation', 'Dịch hoàn thiện'), ('expert_reviewed', 'Đã thẩm định chuyên gia'), ('project_accepted', 'Đã nghiệm thu Dự án'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=50, protected=True, verbose_name='Trạng thái')),
                ('priority', models.CharField(choices=[('0', 'Bình thường'), ('1', 'Cao'), ('2', 'Khẩn')], default='0', max_length=1, verbose_name='Ưu tiên')),
                ('translation_progress', models.IntegerField(default=0, verbose_name='Tiến độ (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_works', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('translation_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.translationpart', verbose_name='Hợp phần dịch thuật')),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_works', to=settings.AUTH_USER_MODEL, verbose_name='Dịch giả')),
            ],
            options={
                'verbose_name': 'Tác phẩm dịch thuật',
                'verbose_name_plural': 'Tác phẩm dịch thuật',
                'db_table': 'translation_works',
                'ordering': ['-created_at'],
            },
        ),
    ]
