# Generated by Django 4.2.7 on 2025-11-18 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationpart',
            options={'ordering': ['name'], 'verbose_name': 'Hợp phần dịch thuật', 'verbose_name_plural': 'Hợp phần dịch thuật'},
        ),
        migrations.RemoveField(
            model_name='translationpart',
            name='leader',
        ),
        migrations.AddField(
            model_name='translationpart',
            name='co_team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_led_parts', to=settings.AUTH_USER_MODEL, verbose_name='Đồng Trưởng nhóm'),
        ),
        migrations.AddField(
            model_name='translationpart',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_parts', to=settings.AUTH_USER_MODEL, verbose_name='Người quản lý'),
        ),
        migrations.AddField(
            model_name='translationpart',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_parts', to=settings.AUTH_USER_MODEL, verbose_name='Trưởng nhóm'),
        ),
        migrations.AddField(
            model_name='translationpart',
            name='work_count',
            field=models.IntegerField(default=0, help_text='Tự động tính từ số lượng works', verbose_name='Số tác phẩm'),
        ),
        migrations.AlterField(
            model_name='translationpart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='translationpart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
    ]
