# Generated by Django 4.2.7 on 2025-11-19 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translators', '0001_initial'),
        ('works', '0002_alter_translationpart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationwork',
            name='translator_user',
            field=models.ForeignKey(blank=True, help_text='Deprecated: Sử dụng translator thay thế', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_translated_works', to=settings.AUTH_USER_MODEL, verbose_name='Dịch giả (User - deprecated)'),
        ),
        migrations.AlterField(
            model_name='translationwork',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_works', to='translators.translator', verbose_name='Dịch giả'),
        ),
    ]
