# Generated by Django 4.2.7 on 2025-11-21 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_translationwork_translator_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên giai đoạn')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã giai đoạn')),
                ('order', models.IntegerField(help_text='Thứ tự sắp xếp (1, 2, 3, 4, 5...)', unique=True, verbose_name='Thứ tự')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Giai đoạn',
                'verbose_name_plural': 'Giai đoạn',
                'db_table': 'stages',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['code'], name='idx_stages_code'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['order'], name='idx_stages_order'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['is_active'], name='idx_stages_active'),
        ),
        migrations.AddField(
            model_name='translationwork',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Giai đoạn thực hiện dịch thuật', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.stage', verbose_name='Giai đoạn'),
        ),
        migrations.AddIndex(
            model_name='translationwork',
            index=models.Index(fields=['translation_part', 'stage'], name='idx_works_part_stage'),
        ),
        migrations.AddIndex(
            model_name='translationwork',
            index=models.Index(fields=['translator', 'state'], name='idx_works_trans_state'),
        ),
        migrations.AddIndex(
            model_name='translationwork',
            index=models.Index(fields=['state'], name='idx_works_state'),
        ),
        migrations.AddIndex(
            model_name='translationwork',
            index=models.Index(fields=['active'], name='idx_works_active'),
        ),
        migrations.AddConstraint(
            model_name='translationwork',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('translation_part', 'stage', 'name'), name='unique_work_part_stage_name', violation_error_message='Đã tồn tại tác phẩm với cùng tên trong hợp phần và giai đoạn này'),
        ),
    ]
