# Generated by Django 4.2.7 on 2025-11-21 08:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0005_populate_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề công việc')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('work_group', models.CharField(choices=[('chung', 'Công việc chung'), ('bien_tap', 'Biên tập'), ('thiet_ke_cntt', 'Thiết kế + CNTT'), ('quet_trung_lap', 'Quét trùng lặp'), ('hanh_chinh', 'Hành chính'), ('tham_dinh_ban_dich_thu', 'Thẩm định bản dịch thử'), ('tham_dinh_cap_cg', 'Thẩm định cấp CG'), ('nghiem_thu_cap_da', 'Nghiệm thu cấp DA'), ('hop_thuong_truc', 'Họp thường trực')], db_index=True, default='chung', max_length=50, verbose_name='Nhóm công việc')),
                ('frequency', models.CharField(choices=[('hang_ngay', 'Hằng ngày'), ('hang_tuan', 'Hằng tuần'), ('hang_thang', 'Hằng tháng'), ('dot_xuat', 'Đột xuất')], db_index=True, default='dot_xuat', max_length=20, verbose_name='Tần suất')),
                ('priority', models.CharField(choices=[('thap', 'Thấp'), ('trung_binh', 'Trung bình'), ('cao', 'Cao'), ('rat_cao', 'Rất cao')], db_index=True, default='trung_binh', max_length=20, verbose_name='Ưu tiên')),
                ('status', models.CharField(choices=[('chua_bat_dau', 'Chưa bắt đầu'), ('dang_tien_hanh', 'Đang tiến hành'), ('hoan_thanh', 'Hoàn thành'), ('khong_hoan_thanh', 'Không hoàn thành'), ('cham_tien_do', 'Chậm tiến độ'), ('hoan_thanh_truoc_han', 'Hoàn thành trước hạn'), ('da_huy', 'Đã hủy'), ('tam_hoan', 'Tạm hoãn')], db_index=True, default='chua_bat_dau', max_length=30, verbose_name='Trạng thái')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Hạn hoàn thành')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('progress_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tiến độ (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người được giao')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Công việc',
                'verbose_name_plural': 'Công việc',
                'db_table': 'work_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['work_group', 'status'], name='idx_tasks_group_status'), models.Index(fields=['assigned_to', 'status'], name='idx_tasks_user_status'), models.Index(fields=['status'], name='idx_tasks_status'), models.Index(fields=['due_date'], name='idx_tasks_due_date'), models.Index(fields=['is_active'], name='idx_tasks_active')],
            },
        ),
    ]
