# Generated by Django 4.2.7 on 2025-11-26 08:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0007_custom_fields_groups_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('start_date', 'Ngày bắt đầu'), ('due_date', 'Hạn hoàn thành'), ('title', 'Tiêu đề công việc'), ('description', 'Mô tả công việc'), ('priority', 'Mức độ ưu tiên'), ('work_group', 'Nhóm công việc'), ('other', 'Khác')], max_length=20, verbose_name='Loại yêu cầu')),
                ('current_value', models.TextField(blank=True, help_text='Giá trị hiện tại của trường cần thay đổi', verbose_name='Giá trị hiện tại')),
                ('requested_value', models.TextField(help_text='Giá trị mới được yêu cầu', verbose_name='Giá trị yêu cầu')),
                ('reason', models.TextField(help_text='Lý do tại sao cần thay đổi thông tin này', verbose_name='Lý do yêu cầu')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã chấp nhận'), ('rejected', 'Đã từ chối'), ('cancelled', 'Đã hủy')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('response_message', models.TextField(blank=True, help_text='Phản hồi từ người xử lý yêu cầu', verbose_name='Phản hồi')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Yêu cầu điều chỉnh công việc',
                'verbose_name_plural': 'Yêu cầu điều chỉnh công việc',
                'db_table': 'task_assignment_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Được giao việc mới'), ('task_updated', 'Công việc được cập nhật'), ('task_completed', 'Công việc hoàn thành'), ('task_overdue', 'Công việc quá hạn'), ('assignment_request', 'Yêu cầu điều chỉnh'), ('assignment_approved', 'Yêu cầu được chấp nhận'), ('assignment_rejected', 'Yêu cầu bị từ chối'), ('evaluation_received', 'Nhận đánh giá từ supervisor'), ('reminder', 'Nhắc nhở')], db_index=True, max_length=30, verbose_name='Loại thông báo')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề thông báo')),
                ('message', models.TextField(verbose_name='Nội dung thông báo')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Đã đọc')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đọc')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Dữ liệu bổ sung cho thông báo (JSON format)', verbose_name='Dữ liệu bổ sung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Thông báo công việc',
                'verbose_name_plural': 'Thông báo công việc',
                'db_table': 'task_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='customfieldvalue',
            name='works_customfieldvalue_task_field_unique',
        ),
        migrations.RemoveConstraint(
            model_name='viewpreference',
            name='works_viewpreference_user_view_type_unique',
        ),
        migrations.AddField(
            model_name='worktask',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Người có quyền chỉnh sửa ngày bắt đầu và hạn hoàn thành', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người giao việc (Assigner)'),
        ),
        migrations.AddField(
            model_name='worktask',
            name='assignment_date',
            field=models.DateTimeField(blank=True, help_text='Thời điểm công việc được giao', null=True, verbose_name='Ngày giao việc'),
        ),
        migrations.AddField(
            model_name='worktask',
            name='evaluation_date',
            field=models.DateTimeField(blank=True, help_text='Thời điểm người giám sát thực hiện đánh giá', null=True, verbose_name='Ngày đánh giá'),
        ),
        migrations.AddField(
            model_name='worktask',
            name='is_assigned',
            field=models.BooleanField(default=False, help_text='True nếu công việc được giao bởi người khác', verbose_name='Đã được giao việc'),
        ),
        migrations.AddField(
            model_name='worktask',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Người có trách nhiệm đánh giá chất lượng công việc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người giám sát (Supervisor)'),
        ),
        migrations.AddField(
            model_name='worktask',
            name='supervisor_comment',
            field=models.TextField(blank=True, help_text='Bình luận của người giám sát về chất lượng công việc', verbose_name='Bình luận đánh giá'),
        ),
        migrations.AddField(
            model_name='worktask',
            name='supervisor_rating',
            field=models.IntegerField(blank=True, help_text='Đánh giá của người giám sát về chất lượng công việc', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá chất lượng (1-5 sao)'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người được giao (Assignee)'),
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together={('task', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='viewpreference',
            unique_together={('user', 'view_type')},
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='assignment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='works.taskassignmentrequest', verbose_name='Yêu cầu điều chỉnh liên quan'),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận'),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi'),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='works.worktask', verbose_name='Công việc liên quan'),
        ),
        migrations.AddField(
            model_name='taskassignmentrequest',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_assignment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý (Assigner)'),
        ),
        migrations.AddField(
            model_name='taskassignmentrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_assignment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu (Assignee)'),
        ),
        migrations.AddField(
            model_name='taskassignmentrequest',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_requests', to='works.worktask', verbose_name='Công việc'),
        ),
        migrations.AddIndex(
            model_name='tasknotification',
            index=models.Index(fields=['recipient', 'is_read'], name='idx_notif_recipient_read'),
        ),
        migrations.AddIndex(
            model_name='tasknotification',
            index=models.Index(fields=['task', 'notification_type'], name='idx_notif_task_type'),
        ),
        migrations.AddIndex(
            model_name='tasknotification',
            index=models.Index(fields=['notification_type'], name='idx_notif_type'),
        ),
        migrations.AddIndex(
            model_name='tasknotification',
            index=models.Index(fields=['is_read'], name='idx_notif_read'),
        ),
        migrations.AddIndex(
            model_name='taskassignmentrequest',
            index=models.Index(fields=['task', 'status'], name='idx_assign_req_task_status'),
        ),
        migrations.AddIndex(
            model_name='taskassignmentrequest',
            index=models.Index(fields=['requester', 'status'], name='idx_assign_req_requester_st'),
        ),
        migrations.AddIndex(
            model_name='taskassignmentrequest',
            index=models.Index(fields=['approver', 'status'], name='idx_assign_req_approver_st'),
        ),
        migrations.AddIndex(
            model_name='taskassignmentrequest',
            index=models.Index(fields=['status'], name='idx_assign_req_status'),
        ),
    ]
