# Generated by Django 4.2.7 on 2025-11-26 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0009_add_redo_evaluation_features'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='worktask',
            name='idx_tasks_user_status',
        ),
        migrations.RemoveField(
            model_name='worktask',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='worktask',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Có thể giao cho nhiều người cùng làm', related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người được giao (Assignees)'),
        ),
    ]
