# Generated by Django 4.2.7 on 2025-11-19 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Họ và tên đệm')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Tên')),
                ('id_card_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Số CMND/CCCD')),
                ('id_card_issue_date', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('id_card_issue_place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nơi cấp')),
                ('workplace', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nơi công tác')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số tài khoản')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên ngân hàng')),
                ('bank_branch', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chi nhánh ngân hàng')),
                ('tax_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã số thuế TNCN')),
                ('active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translator_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản hệ thống')),
            ],
            options={
                'verbose_name': 'Dịch giả',
                'verbose_name_plural': 'Dịch giả',
                'db_table': 'translators',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['full_name'], name='idx_translators_full_name'), models.Index(fields=['id_card_number'], name='idx_translators_id_card'), models.Index(fields=['email'], name='idx_translators_email'), models.Index(fields=['phone'], name='idx_translators_phone'), models.Index(fields=['active'], name='idx_translators_active')],
            },
        ),
    ]
