# Generated by Django 4.2.7 on 2025-11-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='Số hợp đồng')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tổng giá trị')),
                ('advance_payment_1', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tạm ứng lần 1')),
                ('advance_payment_2', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tạm ứng lần 2')),
                ('final_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Quyết toán')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ ký'), ('signed', 'Đã ký'), ('active', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('contract_file', models.FileField(blank=True, upload_to='contracts/', verbose_name='File hợp đồng')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày ký')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Hợp đồng dịch thuật',
                'verbose_name_plural': 'Hợp đồng dịch thuật',
                'db_table': 'translation_contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
