# Generated by Django 4.2.7 on 2025-11-21 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_translationcontract_translator_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên mẫu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('type', models.CharField(choices=[('rich_text', 'Rich Text Editor'), ('word_file', 'File Word (.docx)')], default='rich_text', max_length=20, verbose_name='Loại mẫu')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Nội dung HTML (cho rich_text)')),
                ('file', models.FileField(blank=True, null=True, upload_to='contract_templates/', verbose_name='File Word template')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên file')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mẫu mặc định')),
                ('translation_part', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hợp phần áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_templates', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Mẫu hợp đồng',
                'verbose_name_plural': 'Mẫu hợp đồng',
                'db_table': 'contract_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
