# Generated by Django 4.2.7 on 2025-11-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contracttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationcontract',
            name='advance_payment_1_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tỷ lệ tạm ứng lần 1 (%)'),
        ),
        migrations.AddField(
            model_name='translationcontract',
            name='advance_payment_2_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tỷ lệ tạm ứng lần 2 (%)'),
        ),
        migrations.AddField(
            model_name='translationcontract',
            name='advance_payment_include_overview',
            field=models.BooleanField(default=False, verbose_name='Bao gồm kinh phí bài tổng quan trong tạm ứng'),
        ),
        migrations.AddField(
            model_name='translationcontract',
            name='base_page_count',
            field=models.IntegerField(default=0, verbose_name='Số trang cơ sở'),
        ),
        migrations.AddField(
            model_name='translationcontract',
            name='overview_writing_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kinh phí viết bài tổng quan'),
        ),
        migrations.AddField(
            model_name='translationcontract',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.contracttemplate', verbose_name='Mẫu hợp đồng'),
        ),
        migrations.AddField(
            model_name='translationcontract',
            name='translation_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kinh phí dịch thuật'),
        ),
        migrations.AddField(
            model_name='translationcontract',
            name='translation_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đơn giá dịch thuật'),
        ),
    ]
