# Generated by Django 4.2.7 on 2025-11-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_translationcontract_advance_payment_1_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationcontract',
            name='stage',
            field=models.IntegerField(blank=True, choices=[(1, 'Giai đoạn 1'), (2, 'Giai đoạn 2'), (3, 'Giai đoạn 3'), (4, 'Giai đoạn 4'), (5, 'Giai đoạn 5')], help_text='Giai đoạn thực hiện hợp đồng', null=True, verbose_name='Giai đoạn'),
        ),
        migrations.AddField(
            model_name='translationcontract',
            name='translation_part',
            field=models.CharField(blank=True, help_text='Hợp phần dịch thuật (tự động lấy từ tác phẩm nếu không chỉ định)', max_length=100, null=True, verbose_name='Hợp phần'),
        ),
    ]
