# Generated by Django 4.2.7 on 2025-11-21 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_stage_translationwork_idx_works_part_stage_and_more'),
        ('contracts', '0006_translationcontract_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationcontract',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Giai đoạn thực hiện hợp đồng', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='works.stage', verbose_name='Giai đoạn'),
        ),
        migrations.AlterField(
            model_name='translationcontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ ký'), ('signed', 'Đã ký'), ('active', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='translationcontract',
            name='translation_part',
            field=models.ForeignKey(blank=True, help_text='Hợp phần dịch thuật (tự động lấy từ tác phẩm nếu không chỉ định)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='works.translationpart', verbose_name='Hợp phần'),
        ),
        migrations.AddIndex(
            model_name='translationcontract',
            index=models.Index(fields=['translation_part', 'stage'], name='idx_contracts_part_stage'),
        ),
        migrations.AddIndex(
            model_name='translationcontract',
            index=models.Index(fields=['translator', 'status'], name='idx_contracts_trans_stat'),
        ),
        migrations.AddIndex(
            model_name='translationcontract',
            index=models.Index(fields=['status'], name='idx_contracts_status'),
        ),
        migrations.AddIndex(
            model_name='translationcontract',
            index=models.Index(fields=['contract_number'], name='idx_contracts_number'),
        ),
        migrations.AddConstraint(
            model_name='translationcontract',
            constraint=models.UniqueConstraint(fields=('contract_number',), name='unique_contract_number'),
        ),
    ]
